"""add language to posts

Revision ID: 310bad778a64
Revises: 3bcc5a4c0133
Create Date: 2020-09-16 19:30:40.308092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310bad778a64'
down_revision = '3bcc5a4c0133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
